### ISSUE TITLE
Syntax for elements derived from the footprint (detected patterns, elements defined on a footprint node)

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/pml#10]
WORK IN PROGRESS, NOT YET READY FOR THE REVIEW

An example of the element defined on a footprint node is a building entrance (OpenStreetMap tag: [entrance](https://wiki.openstreetmap.org/wiki/Key:entrance))

```css
facade[@apply_footprint_data](..condtion..) {
    // generate a div for a pattern
    generateFor: pattern, entrance;
    generate: div;
    markup: [
           
        div(item.edge.pattern is rectangle and not item.edge.hasEntrance()) {
            markup: [
                level {
                    markup: [
                        balcony {
                            class: myclass;
                        }
                    ]
                }
            ]
        }

        div(item.edge.pattern is rectangle and item.edge.hasEntrance()) {
            markup: [
                extrude_original {
                    markup: [
                        face(item.front) {
                            markup: [
                                level[0] {
                                    generateFor: entrance;
                                    generate: door;
                                    markup: [
                                        door{
                                            class: entrance_door
                                        }
                                    ]
                                }
                            ]        
                        }
                    ]
                }
            ]
        }

       div(item.center) {
           fromPattern: rectangle;
           level {
               markup: [
                 balcony {
                     class: myclass;
                 }
               ]
           }
       }

    ]
}
```
