### ISSUE TITLE
[building] Syntax for corner items

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/pml#11]
A proposal.

[![image](https://user-images.githubusercontent.com/613295/171031735-7d695628-7bfa-4999-8e11-bc7daad238ee.png)](https://commons.wikimedia.org/wiki/File:Distinctive_corner_windows,_John_Haider_building_-_geograph.org.uk_-_1010661.jpg)
Photo by [Pauline Eccles](https://www.geograph.org.uk/profile/13903), CC-BY-SA 2.0

Suppose a corner item has a `level` item as a neighbor from the right.

For the `level` we would have then:

```
level {
    // if corner items are to be inserted from both sides of the level item
    cornerClass: my_corner_class;
    ....
}
```
or
```
level {
    // if a corner item is to be inserted from the left side of the level item
    cornerClassLeft: my_corner_class;
    ....
}
```
or
```
level {
    // if a corner item is to be inserted from the right side of the level item
    cornerClassRight: my_corner_class;
    ....
}
```

**Comment by vvoovv** [comment]
The neighbor item that shares the corner with the `level` from the above example must also have the attribute _cornerClass_ or cornerClassRight with the same value as in the  `level` from the above example.

**Comment by vvoovv** [comment]
The proposal above isn't consistent.

It leads to incorrect width of items and complexities in calculating the item widths.

Consider the following setup:


```css
level {
    markup: [
        div{
            cornerClassLeft: my_corner;
        }
        entrance{class: my_entrance;}
        div{}
        entrance{class: my_entrance;}
        div{
            cornerClassRight: my_corner;
        }
    ]
}
```

`Div` elements in a `markup` without any child items have the same width by design. When the size of the corner will be subtracted from the leftmost and rightmost `div` items, the resulting width of the leftmost and rightmost `div` items will be smaller than the width of the middle `div`.

**Comment by vvoovv** [comment]
The next iteration of the proposal. Corner element must be defined explicitly through the item `corner`:

```css
level {
    markup: [
        corner{
            class: my_corner;
        }
        entrance{class: my_entrance;}
        div{}
        entrance{class: my_entrance;}
        corner{
            class: my_corner;
        }
    ]
}
```

The adjacent items on the adjacent facades must be of the type `corner` with the same `class` as their neighbors. A corner class can be omitted. In the latter case  the attribute `cornerClass` from a parent item will be used.
